### ISSUE TITLE
Home page application error

### ISSUE THREAD

**Issue by MilanBotka** [id-sk/idsk_elements#56]
Hi,
home page "https://idsk-elements.herokuapp.com/uvod/metodika-ucd" dont work.

And all page related to design manual, are not working too.

mb

**Comment by frkosk** [comment]
Hi, the new official URL is [http://idsk.gov.sk/](http://idsk.gov.sk/).
Alternatively, you can run this page locally from the repository.

**Comment by MilanBotka** [comment]
Ďakujem, riešenie fungovalo. Prosím Vás ako je to právne s používaním komponentov z UK.GOV ? Pripravujeme webové sídlo pre UVZ a chceme tam samozrejme používať komponenty ID-SK iba sa chceme uistiť.

**Comment by MilanBotka** [comment]
Ešte jedna otázka, existuje manuál aj vo forme PDF, alebo *.DOC ?

**Comment by frkosk** [comment]
> Ďakujem, riešenie fungovalo. Prosím Vás ako je to právne s používaním komponentov z UK.GOV ? Pripravujeme webové sídlo pre UVZ a chceme tam samozrejme používať komponenty ID-SK iba sa chceme uistiť.

Samozrejme všetky komponenty sú zahrnuté v ID-SK, môžete ich veselo používať. Mali by prebrať farebnosť a iné vlastnosti z ID-SK. Ak zistíte nezrovnalosti, budeme radi za spätnú väzbu. Zvážte ešte použitie aktuálneho "ID-SK 2.0" ktorý má vlastný repozitár [https://github.com/id-sk/id-sk-frontend](https://github.com/id-sk/id-sk-frontend). Obsahuje fork ostatnej verzie gov.uk

> Ešte jedna otázka, existuje manuál aj vo forme PDF, alebo *.DOC ?

Neviem, že by existovala PDF alebo DOC verzia. Možno vie viac @ljurena

**Comment by MilanBotka** [comment]
Prosím vás táto päta stránky je v poriadku ? Zaujímalo by nás ako je legislatívne vysporiadané preberanie komponentov z UK.gov, pretože sme zodpovedný za návrh služieb. Vďaka
https://idsk.gov.sk/components/footer/preview
![footer](https://user-images.githubusercontent.com/69906425/90751892-fafd3b80-e2d6-11ea-8d4e-66147c256d10.jpg)

**Comment by ljurena** [comment]
> Ešte jedna otázka, existuje manuál aj vo forme PDF, alebo *.DOC ?

Dobrý deň, 

[Jednotný dizajn manuál elektronických služieb verejnej správy.pdf](https://github.com/id-sk/idsk_elements/files/5102830/Jednotny.dizajn.manual.elektronickych.sluzieb.verejnej.spravy.pdf)

Máme IDSK (verziu 1.0) extrahovanú do PDF, V súčastnosti je schválená verzia 2.0 na https://idsk.gov.sk/.

**Comment by MilanBotka** [comment]
Perfektné, Vďaka.

**Comment by frkosk** [comment]
> Prosím vás táto päta stránky je v poriadku ? Zaujímalo by nás ako je legislatívne vysporiadané preberanie komponentov z UK.gov, pretože sme zodpovedný za návrh služieb. Vďaka
> https://idsk.gov.sk/components/footer/preview
> ![footer](https://user-images.githubusercontent.com/69906425/90751892-fafd3b80-e2d6-11ea-8d4e-66147c256d10.jpg)

Neviem povedať, či existuje legislatíva na takúto vec. (cc @ljurena) Máme [komponent slovenskej pätičky](https://idsk.gov.sk/komponenty/hlavicka-paticka) a ten 
 vychádza z gov.uk. Líši sa class atribútom. Variaty s menu sú na [https://idsk.gov.sk/custom-components/footer](https://idsk.gov.sk/custom-components/footer). Správa sa to podobne ako anglická verzia...

Môj osobný názor je, že mať pätičku v legislatíve je kontraproduktívne. Ako by sme potom rozumne menili ID-SK vzhľadom na potreby používateľov.
Aký je na to váš názor?

**Comment by MilanBotka** [comment]
Môj názor na využívanie UK.gov copyright, je taký ako sa spomína tu:
https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/

Predpokladám:
1. že aj SR má právo to voľne používať,
2. postupom času by sa to malo meniť podľa SK UX, čím vzniknú aj odlišné prvky od originálneho copyright-u

Chcel som si to však nechať potvrdiť. Vďaka za profesionálnu odpoveď.
